import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import FileSaver from "file-saver";
import JSONInput from "react-json-editor-ajrm";
import locale from "react-json-editor-ajrm/locale/en";

export default function Home() {
  const [title, setTitle] = useState("");
  const [url, setUrl] = useState("");
  const [response, setResponse] = useState("");
  const [Type, setType] = useState("");
  const [Error, setError] = useState("");

  const AddQrCode = async () => {
    setError("");
    setResponse("");
    await axios
      .post("http://localhost:4500/api/qr", { title, url })
      .then((res) => {
        setResponse(res.data.data);
      })
      .catch((err) => {
        console.log(err?.response?.data);
        setError(err.response.data.message);
      });
  };
  const SaveQR = () => {
    FileSaver.saveAs(`http://localhost:4500${response}`, `${title}.jpeg`, {
      type: "image/jpeg",
    });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>QR PROJECT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1> Title of the QR code : </h1>
        <input
          type="text"
          className="form-control"
          onChange={(e) => {
            setTitle(e.target.value);
          }}
          placeholder="add title"
          value={title}
        />

        <h1> Select the type of the QR code : </h1>
        <select
          type="select"
          onChange={(e) => {
            setType(e.target.value);
          }}
          className="form-control"
          placeholder="Select Type"
          value={Type}
        >
          <option disabled value="">
            {" "}
            Select Type{" "}
          </option>
          <option value="text"> Link/Text </option>
          <option value="JSON"> JSON </option>
        </select>
        {Type == "text" ? (
          <>
            {" "}
            <h1> Link or TEXT of the QR code : </h1>
            <input
              type="text"
              onChange={(e) => {
                setUrl(e.target.value);
              }}
              className="form-control"
              placeholder="add Data"
              value={url}
            />
          </>
        ) : Type == "JSON" ? (
          <>
            {" "}
            <h1> JSON of the QR code : </h1>
            <JSONInput
              id="a_unique_id"
              locale={locale}
              className="JSONAREA"
              width="100%"
              height="250px"
              onChange={(e) => {
                console.log(e.json);
                setUrl(e.json);
              }}
            />
          </>
        ) : (
          ""
        )}
        {Error != "" && (
          <div className="alert alert-danger" role="alert">
            {Error}
          </div>
        )}
        <button
          onClick={() => {
            AddQrCode();
          }}
          className="btn btn-success buttonWithNoMargin"
        >
          Send
        </button>
        <button
          onClick={() => {
            setResponse("");
            setUrl("");
            setTitle("");
            setType("");
            setError("");
          }}
          className="btn btn-danger"
        >
          Reset
        </button>
        {response != "" && (
          <>
            <h1> Generated QR code : </h1>
            <img
              className="rounded d-block"
              src={`http://localhost:4500` + response}
            />
            <button
              className="btn btn-success buttonWithNoMargin"
              onClick={() => {
                SaveQR();
              }}
            >
              {" "}
              Save
            </button>
          </>
        )}
      </div>
    </div>
  );
}
